### ISSUE TITLE
FinalHandler trying to display exceptions is freezing the system

### ISSUE THREAD

**Issue by harikt** [zendframework/zend-expressive#180] opened 2015-11-04 16:58 UTC
Hi, 
I am not sure if this should be called as a bug.

But when there is an exception occured and if the exception is happening from di, the system is getting freezed trying to dump all the di values and configurations :-( . 

Probably there need a better way to handle the exception ?

**Comment by weierophinney** [comment] 2015-11-04 17:01
Can you provide an example? I've not observed it with either Pimple or zend-servicemanager; it could be a circular dependency issue in the exception stack trace, however, which can be… crippling.

**Comment by harikt** [comment] 2015-11-04 17:07
Actually I fear another freeze to do a test live. But this is what I got a freeze and there are more config...

```php
<?php
namespace App\Container;

use Aura\Di\ContainerConfig;
use Aura\Di\Container;
use App\Action\HomePageAction;

class Common extends ContainerConfig
{
    public function define(Container $di)
    {
        $di->params['App\Action\HomePageAction'] = [
            'db' => $di->lazyGet('database'),            
        ];
        
        $di->set('App\Action\HomePageAction', $di->lazyNew('App\Action\HomePageAction'));
    }

    public function modify(Container $di)
    {
    }    
}
```

See I missed to write the service for `db` . And trying to access the service `aura/di` will throw service not found exception which in turn does the freeze :( .

**Comment by harikt** [comment] 2015-11-04 17:57
@weierophinney do you think it will be good to bring the `Doctrine\Common\Util\Debug::dump($entity)` ? http://www.doctrine-project.org/api/common/2.3/source-class-Doctrine.Common.Util.Debug.html#44-70 or may be need register a different finalHandler for it ?

Thank you.

**Comment by harikt** [comment] 2015-11-04 18:17
I was able to replicate the issue, just make sure you have ctrl + c and htop or anything opened to kill ;) .

```php
<?php
namespace App\Action;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Zend\Diactoros\Response\HtmlResponse;

class HomePageAction 
{
    public function __construct($db) 
    {
        $this->db = $db;
    }
    
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next = null)
    {
        $data = [];

        return new HtmlResponse($this->template->render('app::home-page', $data));
    }
}
```

Hope that helps!

I have a request / feedback working with expressive. There need some sort of way to debug things easily. Eg : Middleware when is it called, is it registered etc something like the symfony debug bar which helps to show the event handlers registered / called. ( feature )

**Comment by weierophinney** [comment] 2015-11-04 18:38
@harikt —

> something like the symfony debug bar

That's what Z-Ray is for… Seriously, though, there are lot's of such debug toolbars out there. It sucks that most are not generic, and need to be built for the specific project. That's one thing I like about Z-Ray; generic, *and* pluggable. We're already working on a PSR-7 plugin for it, and will likely build one around middleware signatures (though that one's far harder, as most are not implementing an interface, so we have to look at arguments).

**Comment by weierophinney** [comment] 2015-11-04 18:40
I'll look into this issue soon, and get back to you. I see you're using Aura.Di; I'm going to try with each of the options we currently provide, to see what happens with each. As noted, I've seen stack traces from failed service lookups using zend-servicemanager, and they've never brought the server to its knees, which means we may need to put in some considerations for Aura.Di.

**Comment by xtreamwayz** [comment] 2015-11-04 21:57
I have tried this but I'm sure I'm missing some more info. I added these files and your pull request: https://github.com/zendframework/zend-expressive-skeleton/pull/14

All I get is a fatal error since the template renderer is missing. I think this might be a configuration error or maybe an Aura.DI related bug, but I can't say for sure since I can't reproduce it.

**Comment by harikt** [comment] 2015-11-05 04:22
@xtreamwayz the one you have tried is using HomePageFactory . In the case I don't use the file. We have already added the configuration in 

```php
$di->params['App\Action\HomePageAction'] = [
    'db' => $di->lazyGet('database'),            
];
```

That means it can get the dependency on instantiation of `App\Action\HomePageAction` . You don't need a factory.

**Comment by harikt** [comment] 2015-11-05 06:43
I suggest moving the var_dump on the error template with symfony/var-dumper http://api.symfony.com/2.7/Symfony/Component/VarDumper/VarDumper.html#method_dump . Good one better than Doctrine common dump.

**Comment by xtreamwayz** [comment] 2015-11-05 06:59
@harikt So to get this working I only need to add the pull request, the classes you listed here and this to container.php?

```php
$configClasses = [
    App\Container\Common::class
    // 'Common',
    // 'Dev',
    // 'Prod',
];
```

All I get is the database not found exception and it can't load the HomePageAction. But the system is not freezing:

```
exception 'Aura\Di\Exception\ServiceNotFound' with message 'database' in D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Container.php:277
Stack trace:
#0 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Container.php(257): Aura\Di\Container->getServiceInstance('database')
#1 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Injection\LazyGet.php(65): Aura\Di\Container->get('database')
#2 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Resolver\Resolver.php(239): Aura\Di\Injection\LazyGet->__invoke()
#3 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Resolver\Resolver.php(185): Aura\Di\Resolver\Resolver->mergeParamsEmpty('App\\Action\\Home...', Array)
#4 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Resolver\Resolver.php(131): Aura\Di\Resolver\Resolver->mergeParams('App\\Action\\Home...', Array, Array)
#5 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Injection\Factory.php(105): Aura\Di\Resolver\Resolver->resolve('App\\Action\\Home...', Array, Array)
#6 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Container.php(291): Aura\Di\Injection\Factory->__invoke()
#7 D:\projects\zend-expressive-skeleton-test\vendor\aura\di\src\Container.php(257): Aura\Di\Container->getServiceInstance('App\\Action\\Home...')
#8 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php(548): Aura\Di\Container->get('App\\Action\\Home...')
#9 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php(351): Zend\Expressive\Application->marshalMiddlewareFromContainer('App\\Action\\Home...')
#10 [internal function]: Zend\Expressive\Application->routeMiddleware(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#11 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-stratigility\src\Dispatch.php(81): call_user_func(Array, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#12 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#13 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php(75): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#14 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php(118): Zend\Stratigility\MiddlewarePipe->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Expressive\TemplatedErrorHandler))
#15 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php(432): Zend\Expressive\Application->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#16 D:\projects\zend-expressive-skeleton-test\public\index.php(18): Zend\Expressive\Application->run()
#17 {main}

Next exception 'Zend\Expressive\Exception\InvalidMiddlewareException' with message 'Unable to retrieve middleware "App\Action\HomePageAction" from the container' in D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php:550
Stack trace:
#0 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php(351): Zend\Expressive\Application->marshalMiddlewareFromContainer('App\\Action\\Home...')
#1 [internal function]: Zend\Expressive\Application->routeMiddleware(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#2 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-stratigility\src\Dispatch.php(81): call_user_func(Array, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#3 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#4 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php(75): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#5 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php(118): Zend\Stratigility\MiddlewarePipe->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Expressive\TemplatedErrorHandler))
#6 D:\projects\zend-expressive-skeleton-test\vendor\zendframework\zend-expressive\src\Application.php(432): Zend\Expressive\Application->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 D:\projects\zend-expressive-skeleton-test\public\index.php(18): Zend\Expressive\Application->run()
#8 {main}
```

**Comment by harikt** [comment] 2015-11-05 07:01
yes you are correct. I wonder then what may be the reason I am having.

**Comment by harikt** [comment] 2015-11-05 07:01
oh oh oh, did you removed the HomePageFactory class ? If not please remove it.

**Comment by xtreamwayz** [comment] 2015-11-05 07:19
Yeah I removed it.

**Comment by harikt** [comment] 2015-11-05 07:27
Let me see if I can bring a repo to replicate things.

**Comment by harikt** [comment] 2015-11-05 11:37
Hi @xtreamwayz , 

I have created a repo here : https://github.com/harikt/expressive-issue-180 .

On further testing I noticed a few things 

1. The error handler was removed.
2. It doesn't show any issue on Chrome.
3. It goes out of memory in Firefox.
4. I am using the built in PHP server.


So once you clone, do a composer install .

```
php -S localhost:8000 -t public 
```

and use firefox and let me know if you can see / replicate the error.

Thank you.

**Comment by weierophinney** [comment] 2015-11-05 14:19
@harikt — I have done the following:

- Cloned your repo.
- Run `composer install`
- Used `php -S 0:8080 -t public/` to start a web server
- Visited http://localhost:8080/ in both chrome and firefox

and had no problems.

I then went into `config/autoload/` and did the following:

- Copied `local.php.dist` to `local.php`
- Copied `errorhandler.local.txt` to `errorhandler.local.php`

which enables whoops, so I could see if that was a problem. I visited the home page again in both chrome and firefox… and again, no problems.

When whoops wasn't enabled, the application displayed a well that had the exception stack trace (and previous exceptions) printed out. When whoops was enabled, it displayed the full stack trace. In both cases, I was able to quickly identify the problem (missing configuration/service).

As such, I'm really not sure what's going on.

For the record, I did each of these tests with both 5.5 and 5.6 versions of PHP; no difference in behavior with either.

**Comment by harikt** [comment] 2015-11-05 14:23
@weierophinney :( .

Question : How much is the RAM of your system ?

**Comment by harikt** [comment] 2015-11-05 14:33
I am running on a 4G RAM . Netbeans is opened, browser firefox with ~10 tabs , and shell. I wonder if you guys are running with huge RAM then probably it may not be showing.

As this could not be replicated at your end, I feel this could be closed. But I still think var_dump seems not a good one in error.phtml and fear if the same issue can appear to someone else.

**Comment by xtreamwayz** [comment] 2015-11-05 15:37
> It doesn't show any issue on Chrome.
> It goes out of memory in Firefox.

How is this possible? PHP generates the page and your browser just displays it. I haven't looked at your code yet, but it shouldn't make a difference between browsers since PHP returns the same html code. Are you sure it's not a plugin in your browser that's messing this up?

**Comment by harikt** [comment] 2015-11-05 15:40
not that much plugins installed. 

Only 3 here : REST client, Web developer, Adblock . I am not sure the reason though.

**Comment by xtreamwayz** [comment] 2015-11-05 15:49
@harikt I'm not sure why, but running your code it returns a 15.5MB page with a stack trace. If this happens on your end that might explain the freeze and running out of memory.

**Comment by harikt** [comment] 2015-11-05 15:55
@xtreamwayz I didn't probably get you.

> If this happens on your end that might explain the freeze and running out of memory. 

May be you can expand a bit ? 

Question : You guys seems not having any trouble. I am happy for it. But question is how much is your systems RAM ?

**Comment by xtreamwayz** [comment] 2015-11-05 16:05
This has nothing to do with memory. The problem is for whatever reason a 15.5MB page is returned. Without xdebug it's still 8.5 MB. A normal page is like 10-20 KB, maybe 100-200 KB with a lot of text.

Basically what I get is the same as earlier today: 

```
object(Zend\Expressive\Exception\InvalidMiddlewareException)#93 (7) {
  ["message":protected]=>
  string(76) "Unable to retrieve middleware "App\Action\HomePageAction" from the container"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(89) "D:\projects\expressive-issue-180\vendor\zendframework\zend-expressive\src\Application.php"
  ["line":protected]=>
....
```

and additionally a stack trace of over 8.4MB.

**Comment by xtreamwayz** [comment] 2015-11-05 16:09
Using this in the container.php file displays an error page of only 4. MB:

```
$configClasses = [
    'App\Config\Common',
    //'App\Config\Auth',
];
```

**Comment by xtreamwayz** [comment] 2015-11-05 16:34
Ok, I've removed aura.di and used zend-servicemanger which is already used by zend-view anyway, which you use. I've triggered the same missing middleware action error and I've got only a 1.3 MB output. I guess it's safe to say that the huge memory is caused by using a vardump and trace of aura.di.

**Comment by weierophinney** [comment] 2016-01-06 17:18
Closing, as unable to reproduce.

**Closed by weierophinney** 2016-01-06 17:18 UTC
